name: Publish

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 25
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Build and Publish with Gradle
        env:
          REPOSILITE_USERNAME: ${{ secrets.REPOSILITE_USERNAME }}
          REPOSILITE_TOKEN: ${{ secrets.REPOSILITE_TOKEN }}
        run: |
          ./gradlew publish \
            -PreposiliteUsername="$REPOSILITE_USERNAME" \
            -PreposilitePassword="$REPOSILITE_TOKEN"